import { test, expect } from '@playwright/test'

test('概览统计来自会话与账本，聊天后同步更新', async ({ page }) => {
  await page.goto('/')
  await expect(page).toHaveURL(/#\/overview$/)
  const stats = page.locator('.overview-stats')
  await expect(stats.locator('.stat-value').nth(0)).toContainText('3')
  await expect(stats.locator('.stat-value').nth(1)).toContainText('2')
  await expect(stats.locator('.stat-value').nth(2)).toHaveText('¥7.82')
  await page.getByRole('button', { name: '开始一段对话' }).click()
  await page.getByRole('textbox', { name: '输入消息' }).fill('怎样整理产品说明？')
  await page.getByRole('button', { name: '发送消息', exact: true }).click()
  await expect(page.locator('.message-actions')).toBeVisible()
  await page.getByRole('link', { name: '工作空间概览', exact: true }).click()
  await expect(stats.locator('.stat-value').nth(0)).toContainText('4')
  await expect(stats.locator('.stat-value').nth(1)).toContainText('3')
  await expect(stats.locator('.stat-value').nth(2)).not.toHaveText('¥7.82')
  await expect(page.locator('.overview-conversations')).toContainText('怎样整理产品说明？')
})

test('图表切换计量并区分预留，场景入口只预填草稿', async ({ page }) => {
  await page.goto('/#/overview')
  await page.getByRole('button', { name: /中断调用待核对，08:56/ }).click()
  await expect(page.locator('.chart-selection')).toContainText('¥0.24')
  await expect(page.locator('.chart-selection')).toContainText('预留待核对')
  await page.getByRole('button', { name: 'Token', exact: true }).click()
  await expect(page.locator('.chart-selection')).toContainText('960 Token')
  await page.getByRole('button', { name: /整理产品说明 把复杂的说明/ }).click()
  await expect(page).toHaveURL(/#\/chat$/)
  await expect(page.getByRole('textbox', { name: '输入消息' })).toHaveValue('帮我把产品说明整理成清楚易懂的客服回复。')
  await expect(page.locator('.turn')).toHaveCount(0)
})

test('快捷搜索支持键盘、空结果、关闭还焦与继续已有会话', async ({ page }) => {
  await page.goto('/#/overview')
  const trigger = page.getByRole('button', { name: '搜索页面与会话', exact: true })
  await trigger.click()
  const input = page.getByRole('combobox', { name: '搜索页面与会话' })
  await expect(input).toBeFocused()
  await input.fill('没有匹配的内容')
  await expect(page.getByText('没有找到相关结果', { exact: true })).toBeVisible()
  await input.fill('token')
  await page.keyboard.press('Enter')
  await expect(page).toHaveURL(/#\/usage$/)
  await page.keyboard.press('Control+k')
  await expect(input).toBeFocused()
  await input.fill('产品')
  await page.keyboard.press('ArrowDown')
  await page.keyboard.press('Enter')
  await expect(page).toHaveURL(/#\/chat$/)
  await expect(page.locator('.user-bubble')).toContainText('产品说明')
  await trigger.click()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toBeHidden()
  await expect(trigger).toBeFocused()
})

test('状态随暂停变更，普通身份的概览路由及搜索不显示管理信息', async ({ page }) => {
  await page.goto('/#/settings')
  await page.getByRole('button', { name: '暂停演示自动回复', exact: true }).click()
  await page.getByRole('button', { name: '确认暂停', exact: true }).click()
  await page.getByRole('link', { name: '工作空间概览', exact: true }).click()
  await expect(page.locator('.readiness-card')).toContainText('2/3 已就绪')
  await expect(page.locator('.readiness-card')).toContainText('已暂停新消息生成')
  await page.goto('/#/login')
  await page.getByRole('button', { name: /内部使用者/ }).click()
  await page.goto('/#/overview')
  await expect(page).toHaveURL(/#\/chat$/)
  await page.keyboard.press('Control+k')
  await page.getByRole('combobox', { name: '搜索页面与会话' }).fill('预算')
  await expect(page.getByText('没有找到相关结果', { exact: true })).toBeVisible()
  await page.getByRole('combobox', { name: '搜索页面与会话' }).fill('产品')
  await expect(page.getByRole('listbox', { name: '搜索结果' }).getByRole('option')).toHaveCount(0)
})

test('概览适配窄屏和短屏，手机导航焦点保持在打开的菜单内', async ({ page }) => {
  for (const [width, height] of [[320, 720], [390, 844], [640, 480], [768, 1024], [1024, 768], [1440, 1000], [2560, 1440]]) {
    await page.setViewportSize({ width, height })
    await page.goto('/#/overview')
    await expect(page.getByRole('heading', { name: '工作空间概览', exact: true })).toBeVisible()
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(width)
  }
  await page.setViewportSize({ width: 390, height: 844 })
  const trigger = page.getByRole('button', { name: '打开导航', exact: true })
  await trigger.click()
  await expect(page.locator('.sidebar .brand')).toBeFocused()
  await page.keyboard.press('Shift+Tab')
  await expect(page.locator('.profile-button')).toBeFocused()
  await page.keyboard.press('Tab')
  await expect(page.locator('.sidebar .brand')).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(trigger).toBeFocused()
  await expect(trigger).toHaveAttribute('aria-expanded', 'false')
})
