import { test, expect } from '@playwright/test'
test('聊天发送、停止、预算拒绝与中文输入法事件', async ({ page }) => {
  await page.goto('/#/chat')
  const input = page.getByRole('textbox', {name:'输入消息'})
  await input.fill('输入法尚未确认')
  await input.dispatchEvent('keydown',{key:'Enter',code:'Enter',isComposing:true})
  await expect(page.locator('.turn')).toHaveCount(0)
  await input.fill('如何控制 Token 成本？')
  await page.getByRole('button',{name:'发送消息',exact:true}).click()
  await page.getByRole('button',{name:'停止生成',exact:true}).click()
  await expect(page.locator('.message-notice')).toContainText('未完成')
  await expect(page.locator('.user-bubble')).toHaveText('如何控制 Token 成本？')
  await page.selectOption('#scenario','budget')
  await input.fill('保留这条草稿')
  await page.getByRole('button',{name:'发送消息',exact:true}).click()
  await expect(input).toHaveValue('保留这条草稿')
  await expect(page.locator('.turn')).toHaveCount(1)
})
test('重试中断保留旧答案，第三次完成后禁用重试', async ({page}) => {
  await page.goto('/#/chat')
  await page.getByRole('textbox',{name:'输入消息'}).fill('如何控制成本？')
  await page.getByRole('button',{name:'发送消息',exact:true}).click()
  await expect(page.locator('.message-actions')).toBeVisible()
  const old = await page.locator('.message-text').innerText()
  await page.selectOption('#scenario','disconnect')
  await page.getByRole('button',{name:/重新生成/}).click()
  await expect(page.locator('.message-notice')).toContainText('上一版有效答案')
  await expect(page.locator('.message-text')).toHaveText(old)
  await page.selectOption('#scenario','normal')
  await page.getByRole('button',{name:/重新生成/}).click()
  await expect(page.locator('.attempt-count')).toHaveText('3/3')
  await expect(page.getByRole('button',{name:/重新生成/})).toBeDisabled()
})
test('FE-A03：测试期间保存新地址，旧结果不能标记新地址为可用', async ({page}) => {
  await page.goto('/#/connections')
  // Control the preview clock so the save always occurs inside the pending test.
  await page.clock.install()
  await page.getByRole('button',{name:'模拟连接测试',exact:true}).click()
  await page.locator('input[type=url]').fill('https://changed.example.com/v1')
  await page.getByRole('button',{name:'保存示例配置',exact:true}).click()
  await page.clock.runFor(600)
  await expect(page.locator('.card-header .badge')).toContainText('待模拟测试')
  await page.getByRole('button',{name:'模拟连接测试',exact:true}).click()
  await page.clock.runFor(600)
  await expect(page.locator('.card-header .badge')).toContainText('模拟可用')
})
test('FE-A03：离开连接页面取消尚未完成的测试', async ({page}) => {
  await page.goto('/#/connections')
  await page.clock.install()
  await page.getByRole('button',{name:'模拟连接测试',exact:true}).click()
  await page.getByRole('link',{name:'对话工作台',exact:false}).first().click()
  await page.clock.runFor(600)
  await page.getByRole('link',{name:'模型连接',exact:true}).click()
  await expect(page.locator('.card-header .badge')).toContainText('待模拟测试')
})
test('FE-A04：助手标签可读、可键盘切换，草稿需显式启用', async ({page}) => {
  await page.goto('/#/assistant')
  const basic=page.getByRole('button',{name:'基础配置',exact:true})
  const versions=page.getByRole('button',{name:/版本记录/})
  await expect(basic).toHaveAttribute('aria-pressed','true')
  const contrast=await basic.evaluate(el=>{
    function luminance(text:string){const rgb=text.match(/[\d.]+/g)!.slice(0,3).map(Number).map(v=>v/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4);return rgb[0]*.2126+rgb[1]*.7152+rgb[2]*.0722}
    const s=getComputedStyle(el),l=[luminance(s.color),luminance(s.backgroundColor)].sort((a,b)=>b-a);return (l[0]+.05)/(l[1]+.05)
  })
  expect(contrast).toBeGreaterThanOrEqual(4.5)
  await versions.focus(); await page.keyboard.press('Enter')
  await expect(versions).toHaveAttribute('aria-pressed','true')
  await basic.click()
  await page.getByRole('textbox',{name:'系统提示词',exact:false}).fill('先确认问题，再提供已核实的步骤。')
  await page.getByRole('button',{name:'保存为示例草稿',exact:true}).click()
  const row=page.getByRole('row').filter({hasText:'v1.3'})
  await expect(row).toContainText('草稿')
  await row.getByRole('button',{name:'启用示例',exact:true}).click()
  await expect(row).toContainText('当前启用')
})
test('历史筛选、导出落盘与删除后下载失效', async ({page}) => {
  await page.goto('/#/history')
  await page.getByRole('textbox',{name:'搜索会话'}).fill('不存在的会话')
  await expect(page.getByText('没有找到相关会话', {exact:true})).toBeVisible()
  await page.getByRole('button',{name:'清除筛选',exact:true}).click()
  await page.getByRole('checkbox',{name:'选择 整理产品使用说明',exact:true}).check()
  await page.getByRole('button',{name:/导出示例/}).click()
  const row=page.getByRole('row').filter({hasText:'导出 1 条示例会话'})
  await expect(row).toContainText('示例已完成')
  const event=page.waitForEvent('download')
  await row.getByRole('button',{name:'下载示例',exact:true}).click()
  const download=await event
  const stream=await download.createReadStream()
  const chunks=[];for await (const chunk of stream!) chunks.push(chunk)
  const data=JSON.parse(Buffer.concat(chunks).toString())
  expect(data.demo).toBe(true);expect(data.conversations).toHaveLength(1)
  await page.getByRole('link',{name:'会话记录',exact:true}).first().click()
  await page.getByRole('button',{name:'移除 整理产品使用说明',exact:true}).click()
  await page.getByRole('button',{name:'移除示例',exact:true}).click()
  await page.getByRole('link',{name:'任务中心',exact:true}).click()
  await expect(page.getByRole('row').filter({hasText:'导出 1 条示例会话'})).toContainText('已阻断')
})
test('预算校验、暂停与恢复', async ({page}) => {
  await page.goto('/#/usage')
  await page.getByRole('spinbutton',{name:'每日上限（元）',exact:true}).fill('50')
  await page.getByRole('spinbutton',{name:'每月上限（元）',exact:true}).fill('20')
  await page.getByRole('button',{name:'保存演示额度',exact:true}).click()
  await expect(page.getByRole('status')).toContainText('月额度不小于日额度')
  await page.goto('/#/settings')
  await page.getByRole('button',{name:'暂停演示自动回复',exact:true}).click()
  await page.getByRole('button',{name:'确认暂停',exact:true}).click()
  await page.goto('/#/chat')
  await expect(page.getByRole('textbox',{name:'输入消息'})).toBeDisabled()
  await page.goto('/#/settings')
  await page.getByRole('button',{name:'恢复演示自动回复',exact:true}).click()
  await page.goto('/#/chat')
  await expect(page.getByRole('textbox',{name:'输入消息'})).toBeEnabled()
})
test('普通预览身份仅见个人会话，管理路由被拦截', async ({page}) => {
  await page.goto('/#/login')
  await page.getByRole('button',{name:/内部使用者/}).click()
  await expect(page).toHaveURL(/#\/chat$/)
  await expect(page.getByRole('link',{name:'用量与预算',exact:true})).toHaveCount(0)
  await page.goto('/#/usage')
  await expect(page).toHaveURL(/#\/chat$/)
  await page.goto('/#/history')
  await expect(page.getByRole('button',{name:'打开 我的第一条对话',exact:true})).toBeVisible()
  await expect(page.getByRole('button',{name:'打开 整理产品使用说明',exact:true})).toHaveCount(0)
})
test('手机菜单和管理页返回星球首页', async ({page}) => {
  await page.setViewportSize({width:390,height:844})
  await page.goto('/#/chat')
  await page.getByRole('button',{name:'打开导航',exact:true}).click()
  await page.getByRole('link',{name:'工作空间设置',exact:true}).click()
  await expect(page.getByRole('heading',{name:'工作空间设置',exact:true})).toBeVisible()
  await page.getByRole('link',{name:'返回星球首页',exact:true}).click()
  await expect(page).toHaveURL(/\/space.html$/)
  await expect(page.locator('h1')).toHaveText('EARTH')
})
